//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Prefabs
    {
        public const string BundleName = "prefabs";
        public const string ANNOTATABLE_SCREEN = "Annotatable Screen";
        public const string ARATRAILICON = "AraTrailIcon";
        public const string BOSTER = "Boster";
        public const string BUBBLEEXPLOSION = "BubbleExplosion";
        public const string E3 = "e3";
        public const string E4 = "e4";
        public const string E5 = "e5";
        public const string E6 = "e6";
        public const string E7 = "e7";
        public const string E8 = "e8";
        public const string E9 = "e9";
        public const string E10 = "e10";
        public const string E11 = "e11";
        public const string MAGICAURABLUE = "MagicAuraBlue";
        public const string MEDIAPIPEINIT = "MediapipeInit";
        public const string SWORD = "Sword";
        public const string 拖尾 = "拖尾";
        public const string 拖尾2 = "拖尾2";
        public const string 拖尾3 = "拖尾3";
        public const string 拖尾4 = "拖尾4";
        public const string 拖尾粒子 = "拖尾粒子";
        public const string 昆虫死亡 = "昆虫死亡";
        public const string 炸弹 = "炸弹";
        public const string 炸弹爆炸 = "炸弹爆炸";
    }
    public class Uiprefab
    {
        public const string BundleName = "uiprefab";
        public const string UIAIPANEL = "UIAIPanel";
        public const string UIANNOTATABLESCREENPANEL = "UIAnnotatableScreenPanel";
        public const string UIBGPANEL = "UIBGPanel";
        public const string UIDETECTIONBODYPANEL = "UIDetectionBodyPanel";
        public const string UIDOWNTIMEPANEL = "UIDownTimePanel";
        public const string UIENDPANEL = "UIEndPanel";
        public const string UIMAINPANEL = "UIMainPanel";
        public const string UIMOUSEPANEL = "UIMousePanel";
        public const string UIPLAYERPANEL = "UIPlayerPanel";
        public const string UIRANKINGVERSIONPANEL = "UIRankingVersionPanel";
        public const string UISCOREPANEL = "UIScorePanel";
        public const string UITESTDATAPANEL = "UITestDataPanel";
    }
}
